export * from "@/pages/inital";
export * from "@/pages/home";
export * from "@/pages/profile";
export * from "@/pages/sign-in";
export * from "@/pages/sign-up";
export * from "@/pages/aboutus";
export * from "@/pages/contactus";
export * from "@/pages/pricing";
export * from "@/pages/designpackage";
